version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_dir:/var/lib/postgresql/data/
    env_file: .env.dev
    ports:
      - "5400:5432"
    shm_size: 1g

volumes:
  postgres_data_dir:
