# Generated by Django 5.1.6 on 2025-03-10 10:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('recipient', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('under_review', 'Under Review'), ('false_positive', 'False Positive')], default='to_do', max_length=50)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('internal_data', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('archived_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_employees', to='prototype.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
