# Generated by Django 5.1.6 on 2025-03-10 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_remove_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(db_index=True, max_length=255)),
                ('last_name', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('recipient', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('employer', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('approved', 'Approved'), ('not_approved', 'Not Approved'), ('under_review', 'Under Review'), ('false_positive', 'False Positive')], default='to_do', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
