# Generated by Django 5.1.6 on 2025-03-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
